// <auto-generated />
using System;
using ExemplosPadrõesProjeto.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExemplosPadroesProjeto.Migrations
{
    [DbContext(typeof(ResidenciaContext))]
    [Migration("20190414005200_Romano")]
    partial class Romano
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Casa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Estilo");

                    b.HasKey("Id");

                    b.ToTable("Casas");
                });

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Moveis.Movel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CasaId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Modelo");

                    b.Property<string>("URL");

                    b.HasKey("Id");

                    b.HasIndex("CasaId");

                    b.ToTable("Moveis");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Movel");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Barroco.ArmarioBarroco", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("ArmarioBarroco");

                    b.HasDiscriminator().HasValue("ArmarioBarroco");
                });

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Moveis.Barroco.CadeiraBarroca", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("CadeiraBarroca");

                    b.HasDiscriminator().HasValue("CadeiraBarroca");
                });

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Moveis.Barroco.MesaBarroca", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("MesaBarroca");

                    b.HasDiscriminator().HasValue("MesaBarroca");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Barroco.PoltronaBarroca", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("PoltronaBarroca");

                    b.HasDiscriminator().HasValue("PoltronaBarroca");
                });

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Moveis.CadeiraFuturista", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("CadeiraFuturista");

                    b.HasDiscriminator().HasValue("CadeiraFuturista");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Futurista.ArmarioFuturista", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("ArmarioFuturista");

                    b.HasDiscriminator().HasValue("ArmarioFuturista");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Futurista.PoltronaFuturista", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("PoltronaFuturista");

                    b.HasDiscriminator().HasValue("PoltronaFuturista");
                });

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Moveis.MesaFuturista", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("MesaFuturista");

                    b.HasDiscriminator().HasValue("MesaFuturista");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Romano.ArmarioRomano", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("ArmarioRomano");

                    b.HasDiscriminator().HasValue("ArmarioRomano");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Romano.CadeiraRomano", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("CadeiraRomano");

                    b.HasDiscriminator().HasValue("CadeiraRomano");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Romano.MesaRomano", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("MesaRomano");

                    b.HasDiscriminator().HasValue("MesaRomano");
                });

            modelBuilder.Entity("ExemplosPadroesProjeto.Models.Moveis.Romano.PoltronaRomano", b =>
                {
                    b.HasBaseType("ExemplosPadrõesProjeto.Models.Moveis.Movel");


                    b.ToTable("PoltronaRomano");

                    b.HasDiscriminator().HasValue("PoltronaRomano");
                });

            modelBuilder.Entity("ExemplosPadrõesProjeto.Models.Moveis.Movel", b =>
                {
                    b.HasOne("ExemplosPadrõesProjeto.Models.Casa")
                        .WithMany("Moveis")
                        .HasForeignKey("CasaId");
                });
#pragma warning restore 612, 618
        }
    }
}
